# Generated by Django 4.2.1 on 2023-05-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
