# Generated by Django 4.2.2 on 2023-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
